In [95]:
import numpy as np
import pandas as pd
from pandas_profiling import ProfileReport
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
import seaborn as sns
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.svm import SVC

In [96]:
import os

In [97]:
os.getcwd()

'C:\\Users\\hp'

In [98]:
ls

 Volume in drive C is Windows
 Volume Serial Number is 182E-1B2C

 Directory of C:\Users\hp

19/06/2020  04:44 PM    <DIR>          .
19/06/2020  04:44 PM    <DIR>          ..
10/11/2019  10:15 PM    <DIR>          .anaconda
22/10/2019  08:46 AM    <DIR>          .astropy
02/02/2020  04:40 AM             1,384 .bash_history
10/11/2019  11:15 PM    <DIR>          .conda
10/11/2019  11:15 PM                43 .condarc
25/02/2020  04:49 PM               191 .gitconfig
15/06/2020  09:06 PM    <DIR>          .ipynb_checkpoints
24/09/2019  10:30 AM    <DIR>          .ipython
25/09/2019  08:40 AM    <DIR>          .jupyter
16/10/2019  09:38 AM    <DIR>          .matplotlib
02/02/2020  04:28 AM    <DIR>          .ssh
02/02/2020  04:40 AM             1,272 .viminfo
18/06/2020  08:19 PM    <DIR>          3D Objects
24/09/2019  10:28 AM    <DIR>          Anaconda3
30/10/2019  01:06 AM         4,679,408 assignment.ipynb
22/10/2019  08:29 AM            41,967 boston-data.csv
30/10/2019  10:10 PM   

In [99]:
data_train=pd.read_csv("Pacific_train.csv")
data_test=pd.read_csv("Pacific_test.csv")

In [100]:
data_train.head()

ID                 Name      Date  Time Event Status Latitude  \
0  EP101996            GENEVIEVE  19961003     0           TD    15.0N   
1  EP101988                 JOHN  19880817  1200           TD    18.6N   
2  EP061951              UNNAMED  19510827     0           TS    22.5N   
3  EP101987                 JOVA  19870814  1200           TS    12.8N   
4  EP142007             JULIETTE  20071004  1800           LO    22.4N   

  Longitude  Maximum Wind  Minimum Pressure  ...  Low Wind SW  Low Wind NW  \
0    120.0W            25              1009  ...         -999         -999   
1    107.4W            30              1007  ...         -999         -999   
2    115.1W            45              -999  ...         -999         -999   
3    122.1W            35              -999  ...         -999         -999   
4    113.0W            25              1008  ...            0            0   

   Moderate Wind NE  Moderate Wind SE  Moderate Wind SW  Moderate Wind NW  \
0              -999              -999              -999              -999   
1              -999              -999              -999              -999   
2              -999              -999              -999              -999   
3              -999              -999              -999              -999   
4                 0                 0                 0                 0   

   High Wind NE  High Wind SE  High Wind SW  High Wind NW  
0          -999          -999          -999          -999  
1          -999          -999          -999          -999  
2          -999          -999          -999          -999  
3          -999          -999          -999          -999  
4             0             0             0             0  

[5 rows x 22 columns]

In [101]:
data_test.head()

ID                 Name      Date  Time Event Status Latitude  \
0  EP101985               JIMENA  19850721   600           TD    12.8N   
1  EP151967            PRISCILLA  19671014  1200           TS    13.4N   
2  EP101996            GENEVIEVE  19961004  1800           TD    15.4N   
3  CP011950                 HIKI  19500815  1200           TS    21.4N   
4  EP051956              UNNAMED  19560712     0           HU    20.0N   

  Longitude  Maximum Wind  Minimum Pressure  ...  Low Wind SW  Low Wind NW  \
0    107.7W            30              -999  ...         -999         -999   
1    102.9W            45              -999  ...         -999         -999   
2    119.5W            25              1010  ...         -999         -999   
3    154.4W            45              -999  ...         -999         -999   
4    122.9W            75              -999  ...         -999         -999   

   Moderate Wind NE  Moderate Wind SE  Moderate Wind SW  Moderate Wind NW  \
0              -999              -999              -999              -999   
1              -999              -999              -999              -999   
2              -999              -999              -999              -999   
3              -999              -999              -999              -999   
4              -999              -999              -999              -999   

   High Wind NE  High Wind SE  High Wind SW  High Wind NW  
0          -999          -999          -999          -999  
1          -999          -999          -999          -999  
2          -999          -999          -999          -999  
3          -999          -999          -999          -999  
4          -999          -999          -999          -999  

[5 rows x 22 columns]

In [102]:
data_X_train = data_train[["Date","Time","Maximum Wind","Minimum Pressure","Low Wind NE","Low Wind SE","Low Wind SW","Low Wind NW","Moderate Wind NE","Moderate Wind SE","Moderate Wind SW","Moderate Wind NW","High Wind NE","High Wind SE","High Wind NW","High Wind SW"]]

In [103]:
data_y_train = data_train["Status"]

In [104]:
data_X_train = data_X_train[:10455]
data_y_train = data_y_train[:10455]


In [105]:
data_X_test = data_test[["Date","Time","Maximum Wind","Minimum Pressure","Low Wind NE","Low Wind SE","Low Wind SW","Low Wind NW","Moderate Wind NE","Moderate Wind SE","Moderate Wind SW","Moderate Wind NW","High Wind NE","High Wind SE","High Wind NW","High Wind SW"]]
data_y_test = data_test["Status"]


In [106]:
from sklearn.tree import DecisionTreeClassifier
classifier_1 = DecisionTreeClassifier(criterion = 'entropy')
classifier_1.fit(data_X_train, data_y_train)
z_1 = classifier_1.feature_importances_

In [107]:
y_pred_1 = classifier_1.predict(data_X_test)
y_pred_1 = pd.Series(y_pred_1)

In [108]:
from sklearn.metrics import confusion_matrix
cm_1 = confusion_matrix(data_y_test, y_pred_1)
cm_1

array([[  68,    0,    0,    0,   28,    0,    0,    0,    0,    3,    0],
       [   0,   16,    0,    1,    0,    0,    0,    0,    0,   32,    7],
       [   0,    0,   20,    1,    5,    0,    0,    0,    0,    7,   10],
       [   0,    1,    6, 2717,    0,    0,    0,    0,    1,    0,    0],
       [  15,    0,    0,    0,  592,    0,    0,    0,    0,   94,   14],
       [   0,    0,    0,    0,    1,    0,    0,    0,    0,    0,    0],
       [   0,    0,    2,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    3,    0,    0,    0],
       [   0,    0,    0,    1,    0,    0,    0,    0,    2,    0,    0],
       [   2,   16,    9,    0,  106,    0,    0,    0,    0, 2618,    0],
       [   0,    4,   10,    2,    6,    2,    0,    0,    0,    1, 4032]],
      dtype=int64)

In [109]:
from sklearn.metrics import accuracy_score
acc_1 = accuracy_score(data_y_test, y_pred_1)
acc_1

0.9629842180774749

In [110]:
from sklearn.metrics import recall_score
rs_1 = recall_score(data_y_test, y_pred_1, average = 'macro')
rs_1

0.624990356516892

In [111]:
from sklearn.metrics import precision_score
pr_1 = precision_score(data_y_test, y_pred_1, average = 'macro')
pr_1

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


0.6425095048326764

In [112]:
# Applying k-fold cross validation for DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
accuracies_1 = cross_val_score(estimator = classifier_1, X = data_X_train, y = data_y_train, cv = 10, n_jobs = -1)
accuracies_1.mean()

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


0.9594471599823928

In [113]:
accuracies_1.std()

0.003691783501506388

In [114]:
# Fitting RandomForestClassifier onto the data
from sklearn.ensemble import RandomForestClassifier
classifier_2 = RandomForestClassifier(n_estimators = 1000, criterion = 'entropy')
classifier_2.fit(data_X_train, data_y_train)
z_2 = classifier_2.feature_importances_
z_2

array([0.11099704, 0.00825493, 0.63508267, 0.11066561, 0.02286854,
       0.01618185, 0.01156324, 0.01522813, 0.00579084, 0.0056302 ,
       0.00576298, 0.00532068, 0.01795081, 0.01215406, 0.01071682,
       0.0058316 ])

In [115]:
# Predicting the test values by RandomForestClassifier
y_pred_2 = classifier_2.predict(data_X_test)

In [116]:
y_pred_2 = pd.Series(y_pred_2)

In [117]:
# Evaluating by confusion matrix for RandomForestClassifier
from sklearn.metrics import confusion_matrix
cm_2 = confusion_matrix(data_y_test, y_pred_2)
cm_2

array([[  44,    0,    0,    0,   50,    0,    0,    0,    0,    5,    0],
       [   0,    3,    0,    1,    0,    0,    0,    0,    0,   45,    7],
       [   0,    0,   10,    2,    5,    0,    0,    0,    0,   15,   11],
       [   0,    0,    0, 2725,    0,    0,    0,    0,    0,    0,    0],
       [  14,    0,    0,    0,  559,    0,    0,    0,    0,  126,   16],
       [   0,    0,    0,    0,    1,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    1,    0,    0,    0,    1,    0],
       [   0,    0,    0,    0,    0,    0,    0,    2,    0,    0,    1],
       [   0,    0,    0,    1,    0,    0,    0,    0,    2,    0,    0],
       [   2,   14,    2,    0,  101,    0,    0,    0,    0, 2632,    0],
       [   0,    2,    8,    2,    0,    1,    0,    0,    0,    0, 4044]],
      dtype=int64)

In [118]:
from sklearn.metrics import accuracy_score
acc_2 = accuracy_score(data_y_test, y_pred_2)
acc_2

0.9584887613582018

In [119]:
from sklearn.metrics import recall_score
rs_2 = recall_score(data_y_test, y_pred_2, average = 'macro')
rs_2

0.5272058356423526

In [120]:
from sklearn.metrics import precision_score
pr_2 = precision_score(data_y_test, y_pred_2, average = 'macro')
pr_2

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


0.644835284247444

In [121]:
# Applying k-fold cross validation for RandomForestClassifier
from sklearn.model_selection import cross_val_score
accuracies_2 = cross_val_score(estimator = classifier_2, X = data_X_train, y = data_y_train, cv = 10, n_jobs = -1)
accuracies_2.mean()

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


0.9524681919679481

In [122]:
accuracies_2.std()

0.006279009098261317

In [136]:
# Fitting the NaiveBayesClassifier onto the data
from sklearn.naive_bayes import GaussianNB
classifier_3 = GaussianNB()
classifier_3.fit(data_X_train, data_y_train)


GaussianNB(priors=None, var_smoothing=1e-09)

In [137]:
# Predicting the test values by NaiveBayesClassifier
y_pred_3 = classifier_3.predict(data_X_test)

In [138]:
y_pred_3 = pd.Series(y_pred_3)

In [139]:
# Evaluating by confusion matrix for NaiveBayesClassifier
from sklearn.metrics import confusion_matrix
cm_3 = confusion_matrix(data_y_test, y_pred_3)
cm_3

array([[  99,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,   56,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [  10,   29,    0,    0,    4,    0,    0,    0,    0,    0,    0],
       [   0, 2221,    0,  278,  225,    0,    0,    0,    1,    0,    0],
       [ 660,   42,    0,    0,   13,    0,    0,    0,    0,    0,    0],
       [   1,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   2,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    3,    0,    0,    0],
       [   0,    0,    0,    3,    0,    0,    0,    0,    0,    0,    0],
       [ 434, 2317,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [  40, 3224,    0,    0,  791,    2,    0,    0,    0,    0,    0]],
      dtype=int64)

In [140]:
from sklearn.metrics import accuracy_score
acc_3 = accuracy_score(data_y_test, y_pred_3)
acc_3

0.04294595887135342

In [141]:
from sklearn.metrics import recall_score
rs_3 = recall_score(data_y_test, y_pred_3, average = 'macro')
rs_3

0.28365456061869737

In [142]:
from sklearn.metrics import precision_score
pr_3 = precision_score(data_y_test, y_pred_3, average = 'macro')
pr_3

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


0.1898601175765395

In [143]:
# Applying k-fold cross validation for NaiveBayesClassifier
from sklearn.model_selection import cross_val_score
accuracies_3 = cross_val_score(estimator = classifier_3, X = data_X_train, y = data_y_train, cv = 10, n_jobs = -1)
accuracies_3.mean()

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


0.044191499133065505

In [144]:
accuracies_3.std()

0.009330993785902537

In [150]:
# Fitting SVM Gaussian kernel onto the data
from sklearn.svm import SVC
classifier_4 = SVC(kernel = 'rbf', gamma = 'auto', cache_size = 1000)
classifier_4.fit(data_X_train, data_y_train)
#z_4 = classifier_4.feature_importances_

SVC(C=1.0, cache_size=1000, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [151]:
y_pred_4 = classifier_4.predict(data_X_test)
y_pred_4 = pd.Series(y_pred_4)

In [152]:
# Evaluating by confusion matrix for SVM Gaussian kernel
from sklearn.metrics import confusion_matrix
cm_4 = confusion_matrix(data_y_test, y_pred_4)
cm_4

array([[  23,    0,    0,    0,   14,    0,    0,    0,    0,   10,   52],
       [   0,    0,    0,    1,    0,    0,    0,    0,    0,   10,   45],
       [   0,    0,    0,    2,    0,    0,    0,    0,    0,    4,   37],
       [   0,    0,    0,  658,    0,    0,    0,    0,    0,    0, 2067],
       [   5,    0,    0,    0,  176,    0,    0,    0,    0,   63,  471],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    2],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    3],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    3],
       [   1,    0,    1,    0,   30,    0,    0,    0,    0, 1160, 1559],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    2, 4055]],
      dtype=int64)

In [153]:
from sklearn.metrics import accuracy_score
acc_4 = accuracy_score(data_y_test, y_pred_4)
acc_4

0.5807747489239599

In [154]:
from sklearn.metrics import recall_score
rs_4 = recall_score(data_y_test, y_pred_4, average = 'macro')
rs_4

0.1946469856751221

In [155]:
from sklearn.metrics import precision_score
pr_4 = precision_score(data_y_test, y_pred_4, average = 'macro')
pr_4

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


0.3641960517088819

In [156]:
# Applying k-fold cross validation for SVM Gaussian kernel
from sklearn.model_selection import cross_val_score
accuracies_4 = cross_val_score(estimator = classifier_4, X = data_X_train, y = data_y_train, cv = 10, n_jobs = -1)
accuracies_4.mean()

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


0.5560214374737902

In [157]:
accuracies_4.std()

0.015219990980562764